### ISSUE TITLE
Data path "/polyfills" must be string.

### ISSUE THREAD

**Issue by legendhl** [docgeni/docgeni#499]
Run start:docs or build:docs, the following error is reported:
Error: Schema validation failed with the following errors:
  Data path "/polyfills" must be string.
/Volumes/Work/ydoc/node_modules/@docgeni/core/lib/angular/site-builder.js:311
                    throw new Error(`Child exited with code ${code}`);

**Environment**
Angular 14.2.12
@docgeni/cli 2.0.0 or 2.2.0

**Comment by hexuzhinian** [comment]
This issue may be caused by the version. By default, the polyfills in the automatically generated angular.json file of docgeni are of type array, and when the project starts, the compilation tool can only recognize the polyfills configuration of type string. I'm also experiencing this issue.
**my environment**
Angular 13.2.4
@docgeni/cli 2.2.0

I hope the developers will solve this problem.Thanks!

**Comment by why520crazy** [comment]
Angular changed `polyfills` of config from string to string array in version 15, docgeni support Angular 15 in 2.1.0.

If your Angular version is less than `15`, such as 14.2.12, please downgrade the docgeni to version 2.0.x (< 2.1.0), otherwise, upgrade Angular to 15 as soon as possible, thanks for your feedback!

**Comment by why520crazy** [comment]
We use Angular 14 to test that docgeni version 2.0.1 can work, see https://github.com/docgeni/docgeni-template/tree/ng-14.x
